In [1]:
for i in range(10):
    if i % 5 == 0:
            print('ham')
    elif i % 3 == 0:
            print('eggs')
    else:
            print("spam")
print('finish!')

ham
spam
spam
eggs
spam
ham
eggs
spam
spam
eggs
finish!


In [3]:
for year in range(1950,2021):
    if year < 1989:
        print(f"{year}年は昭和です")
    elif year < 2019:
        print(f'{year}年は平成です')
    else:
        print(f'{year}年は令和です')

1950年は昭和です
1951年は昭和です
1952年は昭和です
1953年は昭和です
1954年は昭和です
1955年は昭和です
1956年は昭和です
1957年は昭和です
1958年は昭和です
1959年は昭和です
1960年は昭和です
1961年は昭和です
1962年は昭和です
1963年は昭和です
1964年は昭和です
1965年は昭和です
1966年は昭和です
1967年は昭和です
1968年は昭和です
1969年は昭和です
1970年は昭和です
1971年は昭和です
1972年は昭和です
1973年は昭和です
1974年は昭和です
1975年は昭和です
1976年は昭和です
1977年は昭和です
1978年は昭和です
1979年は昭和です
1980年は昭和です
1981年は昭和です
1982年は昭和です
1983年は昭和です
1984年は昭和です
1985年は昭和です
1986年は昭和です
1987年は昭和です
1988年は昭和です
1989年は平成です
1990年は平成です
1991年は平成です
1992年は平成です
1993年は平成です
1994年は平成です
1995年は平成です
1996年は平成です
1997年は平成です
1998年は平成です
1999年は平成です
2000年は平成です
2001年は平成です
2002年は平成です
2003年は平成です
2004年は平成です
2005年は平成です
2006年は平成です
2007年は平成です
2008年は平成です
2009年は平成です
2010年は平成です
2011年は平成です
2012年は平成です
2013年は平成です
2014年は平成です
2015年は平成です
2016年は平成です
2017年は平成です
2018年は平成です
2019年は令和です
2020年は令和です


In [4]:
try:
    1/0
except ZeroDivisionError as e:
    print('0では割れません。', e)

0では割れません。 division by zero


In [5]:
names = ['spam', 'ham', 'eggs']
lens = []
for name in names:
    lens.append(len(name))
print(lens)

[4, 3, 4]


In [7]:
names = ['spam', 'ham', 'eggs']
data = [len(name) for name in names]
print(data)

[4, 3, 4]


In [8]:
names = ['spam','ham','eggs']
set_ = {len(name) for name in names}
print(set_)

{3, 4}


In [10]:
names = ['spam', 'ham', 'eggs']
dict_ = {name: len(name) for name in names}
print(dict_)

{'spam': 4, 'ham': 3, 'eggs': 4}


In [12]:
data = [n*n for n in range(10) if n % 2 == 0]
print(data)

[0, 4, 16, 36, 64]


In [14]:
data = [[(i, n*n) for n in range(10) if n%2==0] for i in range(3)]
print(data)

[[(0, 0), (0, 4), (0, 16), (0, 36), (0, 64)], [(1, 0), (1, 4), (1, 16), (1, 36), (1, 64)], [(2, 0), (2, 4), (2, 16), (2, 36), (2, 64)]]


In [ ]:
l = [n*n for n in range(100000)]
type(l), len(l)
# %timeit -n 1000 -r 10  [n*n for n in range(100000)]

In [21]:
g = (n*n for n in range(100000))
type(g)
next(g), next(g), next(g),next(g),next(g)

(0, 1, 4, 9, 16)

In [25]:
with open('sample.txt', 'w') as f:
    f.write('hello\t')
    f.write('world & Python')

In [27]:
f.closed

True

In [28]:
with open('sample.txt', 'r') as f:
    data = f.read()
    print(data)

hello	world & Python


In [31]:
str_ = 'hEllo pyThon'
print(str_.upper())
print(str_.lower())
print(str_.title())

HELLO PYTHON
hello python
Hello Python


In [32]:
str_ = 'hello python'
print(str_.replace('python', 'Java'))

hello Java


In [35]:
str_ = '    spam    ham    eggs    '
print(str_.split())
print(str_.strip())

['spam', 'ham', 'eggs']
spam    ham    eggs


In [39]:
str_ = 'sample.jpg'
print(str_.endswith(('jpg', 'gif', 'png')))

True


In [41]:
'123456789'.isdigit()

True

In [42]:
str_ = 'The quick brown'
len(str_)

15

In [43]:
str_ = 'hello python'
'py' in str_

True

In [44]:
'@'.join(['spam', 'ham', 'eggs'])

'spam@ham@eggs'

In [50]:
lang, num, name = 'python', 10, 'hiro'
print("{}は{}歴{}年です。".format(name, lang, num))
print("{2}年学習した{1}は{0}のものです。".format(name,lang,num))
print("{l}は{num}乗の{n}と申します。".format(l=lang, num=num, n=name))

hiroはpython歴10年です。
10年学習したpythonはhiroのものです。
pythonは10乗のhiroと申します。


In [54]:
import re 

prog = re.compile('(p(yth|l)|z)o[pn]e?')
prog.search('python')


<re.Match object; span=(0, 6), match='python'>

In [56]:
import logging

logging.basicConfig(
        filename = 'example.log',
        level = logging.INFO,
        format = '%(asctime)s:%(levelname)s:%(message)s'
)

logging.debug('デバッグレベル１')
logging.info('INFOレベル')
logging.warning('警告レベル')
logging.error('エラーレベル')
logging.critical('重大なエラー')

In [64]:
from datetime import datetime, date
print(datetime.now())
# datetime.now()
# print(datetime.today())
print(date.today() - date(1985, 7, 6))
datetime.now().isoformat()
print(date.today().strftime('%Y年%m月%d日'))
datetime.strptime('2020年3月7日', '%Y年%m月%d日')

2020-03-07 18:41:33.736103
12663 days, 0:00:00
2020年03月07日


datetime.datetime(2020, 3, 7, 0, 0)

In [66]:
from datetime import date
import pickle

d = {'today': date.today(), 'delta': date(2020, 1, 1) - date.today()}

print(d)
pickle.dumps(d)

{'today': datetime.date(2020, 3, 7), 'delta': datetime.timedelta(days=-66)}


b'\x80\x03}q\x00(X\x05\x00\x00\x00todayq\x01cdatetime\ndate\nq\x02C\x04\x07\xe4\x03\x07q\x03\x85q\x04Rq\x05X\x05\x00\x00\x00deltaq\x06cdatetime\ntimedelta\nq\x07J\xbe\xff\xff\xffK\x00K\x00\x87q\x08Rq\tu.'

In [68]:
from datetime import date
import pickle
d = {'today':date.today(), 'delta':date(2020, 1, 1,) - date.today()}

with open('date.pkl', 'wb') as f:
    pickle.dump(d, f)

In [69]:
with open('date.pkl', 'rb') as f:
    new_d = pickle.load(f)
    print(new_d)

{'today': datetime.date(2020, 3, 7), 'delta': datetime.timedelta(days=-66)}


In [75]:
from pathlib import Path

p = Path()

print(type(p))
p

<class 'pathlib.PosixPath'>


PosixPath('.')

In [78]:
for filepath in p.glob('*.txt'):
    with open(filepath) as f:
        data = f.read()

p = Path('/spam')
p / 'ham' / 'eggs.txt' 

PosixPath('/spam/ham/eggs.txt')

In [79]:
p = Path('date.pkl')
p.exists()

True

In [80]:
p.is_dir()

False

In [84]:
!pip list

Package                            Version  
---------------------------------- ---------
alabaster                          0.7.12   
anaconda-client                    1.7.2    
anaconda-navigator                 1.9.7    
anaconda-project                   0.8.3    
appnope                            0.1.0    
appscript                          1.0.1    
asn1crypto                         0.24.0   
astroid                            2.2.5    
astropy                            3.2.1    
atomicwrites                       1.3.0    
attrs                              19.1.0   
Babel                              2.7.0    
backcall                           0.1.0    
backports.functools-lru-cache      1.5      
backports.os                       0.1.1    
backports.shutil-get-terminal-size 1.0.0    
backports.tempfile                 1.0      
backports.weakref                  1.0.post1
beautifulsoup4                     4.7.1    
bitarray                           0.9.3    
bkcharts  

In [83]:
!pip -V

pip 19.1.1 from /Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pip (python 3.7)


In [110]:
import numpy as np

a = np.array([1, 2, 3])

print(a)
type(a)
a.shape
a.dtype
a[-1]

[1 2 3]


3

In [122]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b.shape
b[1,0]
b[:,2]
b[0,1:]
b[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [96]:
c1 = np.array([1,2,3,4,5,6])
c1
c2 = c1.reshape((3, 2))
c2
c3 = c2.ravel()
c3
c4 = c2.flatten()
c4

array([1, 2, 3, 4, 5, 6])

In [104]:
d = np.array([1,2,3], dtype=np.int16)
d.dtype
d.astype(np.float16)
# d.dtype

array([1., 2., 3.], dtype=float16)